services:
  mafia-postgres:
    image: postgres:15-alpine
    container_name: mafia-postgres
    restart: always
    environment:
      POSTGRES_USER: mafia
      POSTGRES_PASSWORD: mafia
      POSTGRES_DB: mafia_core_db
    volumes:
      - mafia-db-data:/var/lib/postgresql/data
    networks:
      - mafia-network

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3810:3000"
    environment:
      - DATABASE_URL=postgresql://mafia:mafia@mafia-postgres:5432/mafia_core_db
    networks:
      - mafia-network
    depends_on:
      - mafia-postgres

  linkedin-service:
    build: ./backend/linkedin
    container_name: linkedin-service
    restart: always
    networks:
      - mafia-network
    depends_on:
      - mafia-postgres

  frontend:
    build: ./frontend
    container_name: mafia-frontend
    restart: always
    ports:
      - "81:3000"
    networks:
      - mafia-network

volumes:
  mafia-db-data:

networks:
  mafia-network:
    driver: bridge
