services:
  api-gateway:
    build: ./backend/api-gateway
    container_name: mafia-api-gateway
    restart: always
    ports:
      - "3810:3000"
    env_file:
      - ./backend/api-gateway/.env
    networks:
      - mafia-network
      - global-database-network
    depends_on:
      - main-service
      - linkedin-service

  main-service:
    build: ./backend/main
    container_name: mafia-main
    restart: always
    env_file:
      - ./backend/main/.env
    networks:
      - mafia-network
      - global-database-network
    depends_on:
      - frontend

  linkedin-service:
    build: ./backend/linkedin
    container_name: mafia-linkedin
    restart: always
    env_file:
      - ./backend/linkedin/.env
    networks:
      - mafia-network
      - global-database-network

  frontend:
    build: ./frontend
    container_name: mafia-frontend
    restart: always
    ports:
      - "81:3000"
    networks:
      - mafia-network
    env_file:
      - ./frontend/.env

networks:
  mafia-network:
    driver: bridge

  global-database-network:
    external: true
