services:
  api-gateway:
    build: ./backend/api-gateway
    container_name: mafia-api-gateway
    restart: always
    ports:
      - "3810:3000"
    env_file:
      # - ./backend/api-gateway/.env
      - ./backend/api-gateway/.env.local
    volumes:
      - ./backend/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://steiners:steiners@postgres:5432/mafia_db
    networks:
      - mafia-network
      - global-database-network
    depends_on:
      - linkedin-service

  linkedin-service:
    build: ./backend/linkedin
    container_name: mafia-linkedin
    restart: always
    env_file:
      # - ./backend/linkedin/.env
      - ./backend/linkedin/.env.local
    volumes:
      - ./backend/linkedin:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mafia-network
      - global-database-network
  # frontend:
  #   build: ./frontend
  #   container_name: mafia-frontend
  #   restart: always
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "81:3000"
  #   networks:
  #     - mafia-network
  #   env_file:
  #     - ./frontend/.env

networks:
  mafia-network:
    driver: bridge

  global-database-network:
    external: true
