export enum LOGLEVEL {
    ERROR = "ERROR",
    INFO = "INFO",
    WARN = "WARN"
}

export enum APPTYPE {
    LINKEDIN = "LINKEDIN",
    X = "X",
    REDDIT = "REDDIT",
    FACEBOOK = "FACEBOOK",
    INSTAGRAM = "INSTAGRAM",
    THREADS = "THREADS",
    TIKTOK = "TIKTOK"
}

export enum APPSTATUS {
    CONNECTED = "CONNECTED",
    DISCONNECTED = "DISCONNECTED"
}