name: Deploy The Port Mafia

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Run Containerized Stack
    runs-on: [self-hosted, steiners-local]

    steps:
      - name: Checkout Repository Source
        uses: actions/checkout@v4

      - name: Create Frontend Environment File
        run: |
          mkdir -p frontend
          cat <<EOF > frontend/.env
          JWT_PUBLIC_KEY="${{ secrets.JWT_PUBLIC_KEY }}"
          NEXT_PUBLIC_HOME_URL="${{ secrets.HOME_URL }}"
          NEXT_PUBLIC_SERVER_URL="${{ secrets.SERVER_URL }}"
          NEXT_PUBLIC_DEFAULT_REDIRECT_URL="${{ secrets.FRONTEND_URL }}"
          NEXT_PUBLIC_LINKEDIN_CLIENT_ID="${{ secrets.LINKEDIN_CLIENT_ID }}"
          NODE_ENV="production"
          EOF

      - name: Create API Gateway Environment File
        run: |
          mkdir -p backend/api-gateway
          cat <<EOF > backend/api-gateway/.env
          JWT_PUBLIC_KEY="${{ secrets.JWT_PUBLIC_KEY }}"
          JWT_PRIVATE_KEY="${{ secrets.JWT_PRIVATE_KEY }}"
          FRONTEND_URL="${{ secrets.FRONTEND_URL }}"
          EOF

      - name: Standardize and Rebuild Containers
        run: |
          docker compose down --remove-orphans
          docker compose up --build -d
          docker image prune -f